### ISSUE TITLE
请问编写命令行应用，是不是需要学习终端io的知识？

### ISSUE THREAD

**Issue by itfanr** [turingou/douban.fm#130]
douban.fm或者vim等类似的软件。还有我想问`function Fm() `这个函数的主调函数在哪里？因为我从index.js里面看到入口在这里，但是我找了半天没发现只看到做了初始化，没看到从哪里调用的菜单什么的。。。求指导。

谢谢

**Comment by dearrrfish** [comment]
https://github.com/turingou/douban.fm/blob/master/bin/cli
调用在这里

**Comment by itfanr** [comment]
@dearrrfish   谢谢啊！
