### ISSUE TITLE
无法登陆账号

### ISSUE THREAD

**Issue by designer9418** [turingou/douban.fm#133]
**豆瓣FM版本：**0.3.0
**Node版本：**0.10.36
**系统版本：**OSX 10.10.2 / Darwin 14.1.0
**问题：**正确输入账号和密码后显示

    douban.fm v0.3.0 error
      ↳  {}

**补充：**
+ 密码仅包含大小写字母和数字
+ Node v0.12.0 安装失败

**Comment by turingou** [comment]
douban.fm 依赖的模块暂不支持 v0.11.x 和 v0.12.x
你是 clone master 分支的代码吗？建议使用上一个稳定版本，直接 sudo npm install douban.fm -g

**Comment by designer9418** [comment]
用的是这个：

    npm install douban.fm -g --disturl=http://dist.u.qiniudn.com --registry=http://r.cnpmjs.org

**Comment by turingou** [comment]
可以执行 core.douban.fm config 然后输入自己的账户密码试试看，这样可以把具体的错误抛出来

**Comment by designer9418** [comment]
![90079625-0a3a-482b-820b-998c8d9e3839](https://cloud.githubusercontent.com/assets/11269828/6440708/d7421528-c11a-11e4-8603-bcfd1bba0143.png)

现在装回v0.2了 可以正常使用了

**Comment by turingou** [comment]
我标记一个 bug。最近比较忙，没时间维护这个模块 :) 果断时间来修复一下

**Comment by gracece** [comment]
我也是相同的情况，无法登录。
