### ISSUE TITLE
编译出错。。

### ISSUE THREAD

**Issue by holidaybattle** [turingou/douban.fm#137]
/
> speaker@0.2.1 install E:\TDDOWNLOAD\douban.fm-master\node_modules\player\node_
modules\speaker
> node-gyp rebuild

E:\TDDOWNLOAD\douban.fm-master\node_modules\player\node_modules\speaker>if not d
efined npm_config_node_gyp (node "E:\nodejs\node_modules\npm\bin\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
  win32.c
  output.vcxproj -> E:\TDDOWNLOAD\douban.fm-master\node_modules\player\node_mod
  ules\speaker\build\Release\\liboutput.lib
  binding.cc
E:\TDDOWNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\node_mo
dules\nan\nan.h(672): warning C4244: “return”: 从“int64_t”转换到“int”，可
能丢失数据 [E:\TD
DOWNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\bindin
g.vcxproj]
..\src\binding.cc(131): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(132): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(133): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(134): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(135): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(136): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(137): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(138): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(139): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
..\src\binding.cc(140): error C2661: “v8::Object::Set”: 没有重载函数接受 3 个
参数 [E:\TDDO
WNLOAD\douban.fm-master\node_modules\player\node_modules\speaker\build\binding.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "E:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\TDDOWNLOAD\douban.fm-master\node_modules\player\node_modules\spe
aker
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

**Comment by turingou** [comment]
Windows ? 目前 douban.fm 的依赖模块都不能很好的在 Windows 上工作

**Comment by holidaybattle** [comment]
是的，我装的另一个网易云也是一样的错误。感谢回复
