### ISSUE TITLE
Mac os x  安装出错了 speaker@0.2.1 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by zhangda89** [turingou/douban.fm#141]
error Darwin 14.1.0
15134 error argv "node" "/usr/local/bin/npm" "install" "douban.fm" "-g" "--disturl=http://dist.u.qiniudn.com" "--registry=http://r.cnpmjs.org"
15135 error node v0.12.2
15136 error npm  v2.7.5
15137 error code ELIFECYCLE
15138 error speaker@0.2.1 install: `node-gyp rebuild`
15138 error Exit status 1
15139 error Failed at the speaker@0.2.1 install script 'node-gyp rebuild'.
15139 error This is most likely a problem with the speaker package,
15139 error not with npm itself.
15139 error Tell the author that this fails on your system:
15139 error     node-gyp rebuild
15139 error You can get their info via:
15139 error     npm owner ls speaker
15139 error There is likely additional logging output above.

**Comment by turingou** [comment]
npm 中的稳定版本暂时不支持 Node v0.11.x 与 Node v0.12.x

**Comment by turingou** [comment]
对 Node.js v0.12.x 的支持将会在下个版本发布
