### ISSUE TITLE
建议将 UI 与控制逻辑解耦

### ISSUE THREAD

**Issue by aleung** [turingou/douban.fm#144]
我在使用的是 [FMD](https://github.com/aleung/fmd/tree/fmd-python) + [FMWeb](https://github.com/aleung/fmweb) 来播放豆瓣电台，FMD 是作为 deamon 运行的播放器，FMWeb 是基于 web 的UI，这样就可以用手机浏览器来遥控播放。

FMD 原作者将项目语言转成 C，我现在用 node.js 比较多，所以有意基于你的项目开发一个 web 的版本，这样我就可以通过手机控制播放的方式来使用了。

大概浏览了代码，发现 fm.js 里面包含了CLI 界面与播放控制逻辑，如果能够解耦，那么适配不同的界面就会比较方便。

你觉得这样想法怎样？看到这个项目近期没有 commit，下一步有什么计划吗？如果我去做修改，不知道与你正在进行的工作会不会有冲突？

**Comment by guo-yu** [comment]
sdk 部分的代码是解耦的，详细的依赖模块可以看看 package.json

**Comment by aleung** [comment]
Ok, 那我就另外建一个项目，依赖 sdk。可能会参考这个项目的部分代码，但就不考虑复用了。
